-- Seed ~500 demo items for Home/Top Picks
-- NOTE: Intended for development/testing environments. Review before applying to production.

DO $$
DECLARE
  v_count int := 0;
  v_user uuid;
  v_category uuid;
  v_city record;
  v_conditions text[] := ARRAY['new','like_new','good','fair','poor'];
  v_condition text;
  v_currencies text[] := ARRAY['GEL','USD','EUR'];
  v_currency text;
BEGIN
  -- Ensure we have users and active categories to bind items to
  IF (SELECT count(*) FROM public.users) = 0 THEN
    RAISE NOTICE 'Skipping demo item seed: no users in public.users';
    RETURN;
  END IF;

  IF (SELECT count(*) FROM public.categories WHERE is_active = true) = 0 THEN
    RAISE NOTICE 'Skipping demo item seed: no active categories in public.categories';
    RETURN;
  END IF;

  IF (SELECT count(*) FROM public.cities) = 0 THEN
    RAISE NOTICE 'Skipping demo item seed: no cities in public.cities';
    RETURN;
  END IF;

  WHILE v_count < 500 LOOP
    -- Pick random user, category, and city
    SELECT id INTO v_user FROM public.users ORDER BY random() LIMIT 1;
    SELECT id INTO v_category FROM public.categories WHERE is_active = true ORDER BY random() LIMIT 1;
    SELECT id, center_lat, center_lng INTO v_city FROM public.cities ORDER BY random() LIMIT 1;

    -- Random condition and currency
    v_condition := v_conditions[1 + floor(random() * array_length(v_conditions, 1))::int];
    v_currency := v_currencies[1 + floor(random() * array_length(v_currencies, 1))::int];

    INSERT INTO public.items (
      user_id,
      title,
      description,
      category_id,
      condition,
      price,
      currency,
      status,
      location_lat,
      location_lng,
      created_at,
      updated_at
    )
    VALUES (
      v_user,
      'Demo swap item #' || v_count,
      'Autogenerated demo item used to populate Top Picks and Home screen. Safe to delete in production.',
      v_category,
      v_condition,
      round((10 + random() * 190)::numeric, 2),
      v_currency,
      'available',
      v_city.center_lat + (random() - 0.5) * 0.1,
      v_city.center_lng + (random() - 0.5) * 0.1,
      now() - (random() * 30 || ' days')::interval,
      now() - (random() * 30 || ' days')::interval
    );

    v_count := v_count + 1;
  END LOOP;
END;
$$;

